# docker-compose
version: '3.7'
services:
  app:
    container_name: 'samava-frontEnd-production'
    mem_reservation: 2g
    build:
      context: .
      dockerfile: ./production.dockerfile
    command: sh -c "npm start"
    ports:
      - 8181:8181
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
volumes:
  node_modules:
